require 5.010;
use strict;
use warnings FATAL => 'all';
use Test::More;
use Stats::LikeR 't_test';

# Cross-validation of t_test() against R's stats::t.test() and SciPy's
# scipy.stats.ttest_*, using those projects' own test suites and man-page
# examples rather than cases invented here.  t/t_test.t already covers the call
# shapes, the croak messages and leak checking; this file does not repeat them.
#
# PROVENANCE
# ----------
# The frozen tables live in the DATA section at the end of this file: R's half
# first, then SciPy's after a marker line.  Neither generator is ever run by the
# test, so the distribution installs and tests with no R and no python present.
#
# R 4.6.1 (2026-06-24), regenerated by t/t_test.R.R:
#
#   src/library/stats/man/t.test.Rd
#       t.test(1:10, y = c(7:20))          (the page's own "P = .00001855")
#       t.test(1:10, y = c(7:20, 200))     (the page's own "P = .1245")
#       with(mtcars, t.test(mpg[am == 0], mpg[am == 1]))
#       t.test(sleep$extra), and the paired wide-format sleep test
#   tests/reg-tests-1a.R:4529
#       "t.test with one group of size one", both orientations, var.equal=TRUE
#       -- these failed outright in R 2.4.0, so they are a real regression case
#       and not a synthetic edge
#   tests/reg-tests-2.R:3199
#       print(t.test(1:28), digits = 3)
#   tests/reg-tests-1e.R:1985
#       t.test(<Inf>...), PR#18901 -- these errored in R <= 4.5.1
#
# SciPy 1.18.0, scipy/stats/tests/test_stats.py, reproduced at SciPy's own
# values and tolerances:
#
#   TestTTest_1samp                 X1 = [-1,0,1] at mu 0, 1, 2 and X2 = [0,1,2],
#                                   upstream comment "Recomputed statistics and
#                                   p-values with R t.test"
#   TestTTestIndMore
#     .test_ttest_ind_with_uneq_var  [1,2,3] and [1,2,3,4] against [1.1,2.9,4.2],
#                                    upstream comment "check vs. R `t.test`"
#     .test_ttest_ind_nan_2nd_arg    the NaN-dropped pair, upstream comment
#                                    "this is consistent with R"
#     .test_ttest_uniform_pvalues    t.test(c(2,3,5), c(1.5), var.equal=TRUE) --
#                                    a second group of size ONE
#     .test_ttest_ind_zero_division  zeros vs ones, and a sample against itself
#   TestTTestRel.test_ttest_rel      the linspace pair, paired
#   TestTTestCI                      the 11-vs-13 sample at conf.level 0.9,
#                                    whose reference values SciPy itself
#                                    obtained from R
#
# Every documented case is then crossed over the whole argument space --
# alternative x var_equal x mu x conf.level x paired -- because a reference case
# exercised only at its defaults pins one code path out of dozens.  That is what
# takes two dozen upstream cases to the 273 comparisons in the table.
#
# WHAT WRITING THIS FILE TURNED UP
# --------------------------------
# t_test() accepted only the underscored 'conf_level' and 'var_equal', so the
# 'conf.level' its own documentation lists -- and the 'var.equal' R spells it
# with -- were a croak rather than an argument, even though every sibling in the
# module (var_test, wilcox_test, prop_test, glm, ...) already took both.  Fixed
# in LikeR.xs; the section near the end keeps both spellings tested.
#
# TOLERANCES
# ----------
# $TOL_R applies to everything joined against the R table, whose values carry
# 17 significant digits.  Worst disagreements actually measured over the
# 2400-odd comparisons here, on each NV width in the local matrix:
#
#                    double     long double / __float128
#   statistic        1.83e-15   1.85e-12
#   p.value          6.46e-15   2.06e-12
#   estimate         6.51e-16   2.08e-12
#   conf.int         2.34e-13   1.55e-12
#   df               8.61e-16   5.63e-16
#
# The wider widths are the worse ones here, and that is expected rather than a
# defect: the linspace inputs below are not dyadic, so on a long-double or
# quadmath perl the literals parse to values a relative 1e-17 away from the
# doubles R and numpy saw, and the statistic carries that straight through.  It
# is the input that differs, not the arithmetic -- the same tables on the same
# integer-valued inputs (sleep, mtcars, 1:10) agree to 1 ulp on every width.
#
# The limit is set from the widest width's worst case with two orders of
# headroom, since neither Windows' nor a BSD's long double can be measured
# here.  Do not widen it to make a failure go away.
#
# $TOL_SCIPY is looser only because SciPy's literals are shorter, not because
# anything is less accurate: the TestTTestCI block carries 7 digits and says so
# upstream ("rtol = 1e-7  # only 7 digits in reference").
#
# The linspace inputs are reproduced as start + i*step with the last element
# pinned to the stop, which is what numpy's linspace computes, so the vector
# here really is SciPy's.  Its elements are not dyadic, so on a long-double or
# quadmath perl they parse to values a relative 1e-17 from the doubles R and
# numpy saw.  Both statistics are well conditioned in those inputs -- the two
# samples differ by ~0.01 throughout, not by an ulp, so nothing cancels -- and
# that perturbation stays well inside $TOL_R.  Do not widen these to make a
# failure go away.
my $TOL_R     = 1e-10;
my $TOL_SCIPY = 1e-7;

#
# The input vectors, exactly as the two references have them.
#
my @MTCARS_AM0 = (21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8, 16.4, 17.3,
                  15.2, 10.4, 10.4, 14.7, 21.5, 15.5, 15.2, 13.3, 19.2);
my @MTCARS_AM1 = (21, 21, 22.8, 32.4, 30.4, 33.9, 27.3, 26, 30.4, 15.8, 19.7,
                  15, 21.4);
my @SLEEP1 = (0.7, -1.6, -0.2, -1.2, -0.1, 3.4, 3.7, 0.8, 0, 2);
my @SLEEP2 = (1.9, 0.8, 1.1, 0.1, -0.1, 4.4, 5.5, 1.6, 4.6, 3.4);

# numpy.linspace(start, stop, n): start + i*step, with the last element set
# exactly to stop.  Reproduced rather than transcribed so the 100-element
# vectors do not have to be pasted at 17 digits apiece.
sub linspace {
	my ($a, $b, $n) = @_;
	my $step = ($b - $a) / ($n - 1);
	my @v = map { $a + $step * $_ } 0 .. $n - 1;
	$v[$n - 1] = $b;
	return \@v;
}

# TestTTestCI's own 11- and 13-element samples, copied from the R snippet in
# that class's comment block.
my @CI_A = (0.88236329, 0.97318744, 0.4549262, 0.97893335, 0.0606677,
            0.44013366, 0.55806018, 0.40151434, 0.14453315, 0.25860601,
            0.20202162);
my @CI_B = (0.93455277, 0.42680603, 0.49751939, 0.14152846, 0.711435,
            0.77669667, 0.20507578, 0.78702772, 0.94691855, 0.32464958,
            0.3873582, 0.35187468, 0.21731811);

# tag => [x] or [x, y]
my %INPUT = (
	'man.1to10.7to20'          => [ [1 .. 10], [7 .. 20] ],
	'man.1to10.outlier'        => [ [1 .. 10], [7 .. 20, 200] ],
	'man.mtcars.am'            => [ \@MTCARS_AM0, \@MTCARS_AM1 ],
	'man.sleep.all'            => [ [ @SLEEP1, @SLEEP2 ] ],
	'man.sleep.paired'         => [ \@SLEEP1, \@SLEEP2 ],
	'man.sleep.unpaired'       => [ \@SLEEP1, \@SLEEP2 ],
	'reg2.1to28'               => [ [1 .. 28] ],
	'reg1a.n1.xfirst'          => [ [23], [25, 29, 27, 30, 30] ],
	'reg1a.n1.yfirst'          => [ [25, 29, 27, 30, 30], [23] ],
	'edge.two.pts'             => [ [1, 2] ],
	'edge.2v2'                 => [ [1, 2], [3, 4] ],
	'edge.2v3'                 => [ [1, 2], [3, 4, 5] ],
	'edge.samemean'            => [ [1, 2, 3], [0, 2, 4] ],
	'edge.onezerovar'          => [ [5, 5, 5], [1, 2, 3] ],
	'scipy.uneqvar.a'          => [ [1, 2, 3], [1.1, 2.9, 4.2] ],
	'scipy.uneqvar.b'          => [ [1, 2, 3, 4], [1.1, 2.9, 4.2] ],
	'scipy.n1.235.15'          => [ [2, 3, 5], [1.5] ],
	'scipy.nan2nd'             => [ [1, 2, 1, 2], [2, 3, 4] ],
	'scipy.X1'                 => [ [-1, 0, 1] ],
	'scipy.X2'                 => [ [0, 1, 2] ],
	'scipy.rel.linspace'       => [ linspace(1, 100, 100), linspace(1.01, 99.989, 100) ],
	'scipy.ind.linspace'       => [ linspace(5, 105, 100), linspace(1, 100, 100) ],
	'scipy.ind.linspace.uneqn' => [ linspace(5, 105, 100), linspace(1, 100, 25) ],
	'scipy.ci.11v13'           => [ \@CI_A, \@CI_B ],
);

my $INF = 9**9**9;

# Relative compare that also copes with the exact 0, the NA and the +-Inf the
# references report at the boundaries.  Returns (ok, relative error).
sub close_to {
	my ($got, $exp, $name, $tol) = @_;
	if ($exp eq 'NA') {
		return (ok(!defined $got || $got != $got, "$name is NA"), undef);
	}
	if ($exp eq 'Inf' || $exp eq '-Inf') {
		my $want = $exp eq 'Inf' ? $INF : -$INF;
		return (ok(defined $got && $got == $want, "$name is $exp"), undef);
	}
	if (!defined $got) {
		fail("$name: got undef, expected $exp");
		return (0, undef);
	}
	my $err = $exp == 0 ? abs($got) : abs($got - $exp) / abs($exp);
	my $ok = $err <= $tol;
	ok($ok, $name)
		or diag(sprintf 'got %.17g, expected %s, rel err %.4g (tol %.3g)',
			$got, $exp, $err, $tol);
	return ($ok, $err);
}

my %worst;
sub note_worst {
	my ($field, $err) = @_;
	$worst{$field} = $err if defined $err && $err > ($worst{$field} || 0);
}

# A label is  tag|form|alternative|ve=..|mu=..|cl=..|p=..  with the ve and p
# parts absent for the one-sample form, which is spelled 1s.
sub options_from {
	my ($label) = @_;
	my @part = split /\|/, $label;
	my $tag  = shift @part;
	my $form = shift @part;
	my %opt;
	for my $p (@part) {
		if    ($p =~ /\Amu=(\S+)\z/) { $opt{mu}           = $1 + 0 }
		elsif ($p =~ /\Acl=(\S+)\z/) { $opt{'conf.level'} = $1 + 0 }
		elsif ($p =~ /\Ave=(\d)\z/)  { $opt{var_equal}    = $1 + 0 }
		elsif ($p =~ /\Ap=(\d)\z/)   { $opt{paired}       = $1 + 0 }
		else                         { $opt{alternative}  = $p }
	}
	return ($tag, $form, \%opt);
}

sub run_r_case {
	my ($label, $exp) = @_;
	my ($tag, $form, $opt) = options_from($label);
	my $in = $INPUT{$tag} or do { fail("no input registered for '$tag'"); return };
	my @args = $form eq '1s' ? ($in->[0]) : ($in->[0], $in->[1]);
	my $r = eval { t_test(@args, %$opt) };
	if ($@) { fail("R $label: t_test died: $@"); return }

	my ($stat, $param, $pval, $est, $lo, $hi) = @$exp;
	for my $f (['statistic', $stat], ['df', $param], ['p.value', $pval]) {
		my (undef, $e) = close_to($r->{ $f->[0] }, $f->[1], "R $label: $f->[0]", $TOL_R);
		note_worst($f->[0], $e);
	}
	# One-sample and paired tests return a single 'estimate'; the two-sample
	# test returns 'estimate.x' and 'estimate.y', matching R's own
	# names(estimate) for that case ("mean of x", "mean of y").
	my @est_exp = split /,/, $est;
	my @est_got = @est_exp > 1 ? ($r->{'estimate.x'}, $r->{'estimate.y'})
	                           : ($r->{estimate});
	is(scalar(grep { defined } @est_got), scalar @est_exp, "R $label: estimate count");
	for my $i (0 .. $#est_exp) {
		my (undef, $e) = close_to($est_got[$i], $est_exp[$i],
			"R $label: estimate[$i]", $TOL_R);
		note_worst('estimate', $e);
	}
	return if $lo eq '-';
	my $ci = $r->{'conf.int'};
	ok(ref $ci eq 'ARRAY', "R $label: conf.int present") or return;
	for my $i (0, 1) {
		my (undef, $e) = close_to($ci->[$i], ($i ? $hi : $lo),
			"R $label: conf.int[$i]", $TOL_R);
		note_worst('conf.int', $e);
	}
}

# SciPy's cases in SciPy's own terms, so this file fails if either reference is
# contradicted rather than only R.
sub run_scipy_case {
	my ($what, $v) = @_;
	my ($tag, $form, $opt) = options_from($what);
	my $in = $INPUT{$tag} or do { fail("no input registered for '$tag'"); return };
	my @args = $form eq '1s' ? ($in->[0]) : ($in->[0], $in->[1]);
	my $r = eval { t_test(@args, %$opt) };
	if ($@) { fail("scipy $what: t_test died: $@"); return }
	my ($stat, $df, $p, $lo, $hi) = @$v;
	close_to($r->{statistic}, $stat, "scipy $what: statistic", $TOL_SCIPY);
	close_to($r->{df},        $df,   "scipy $what: df",        $TOL_SCIPY)
		unless $df eq '-';
	close_to($r->{'p.value'}, $p,    "scipy $what: p.value",   $TOL_SCIPY);
	return if !defined $lo || $lo eq '-';
	close_to($r->{'conf.int'}[0], $lo, "scipy $what: conf.int lo", $TOL_SCIPY);
	close_to($r->{'conf.int'}[1], $hi, "scipy $what: conf.int hi", $TOL_SCIPY);
}

my ($rows_R, $rows_scipy, $section) = (0, 0, 'R');
while (my $line = <DATA>) {
	next if $line =~ /\A\s*#/ || $line !~ /\S/;
	chomp $line;
	if ($line eq 'SCIPY-SECTION') { $section = 'SCIPY'; next }
	if ($section eq 'R') {
		my ($label, undef, @v) = split /\t/, $line;
		$rows_R++;
		run_r_case($label, \@v);
	}
	else {
		my ($what, @v) = split /\t/, $line;
		$rows_scipy++;
		run_scipy_case($what, \@v);
	}
}

cmp_ok($rows_R,     '>', 250, "R reference cases exercised ($rows_R)");
cmp_ok($rows_scipy, '>',   8, "SciPy reference cases exercised ($rows_scipy)");

#
# Cases no table can hold, because the reference's answer is an error rather
# than a number -- and where R and SciPy differ by design.  Both behaviours are
# recorded so that changing either is deliberate.
#
# scipy.stats.ttest_ind(zeros(3), ones(3)) warns "Precision loss occurred" and
# returns (-inf, 0.0); R's t.test(rep(0,3), rep(1,3)) is a hard error, "data
# are essentially constant".  t_test() follows R, which is what it is modelled
# on.  Likewise a sample against itself, where SciPy returns NaN.
{
	my $r = eval { t_test([0, 0, 0], [1, 1, 1]) };
	ok(!defined $r, 'zero variance in both groups is fatal, as in R');
	like($@, qr/essentially constant/,
		"...with R's own 'data are essentially constant' wording");

	$r = eval { t_test([0, 0, 0], [0, 0, 0]) };
	ok(!defined $r, 'a sample against itself is fatal, as in R');

	$r = eval { t_test([4], mu => 3) };
	ok(!defined $r, 'a one-sample test on n = 1 is fatal, as in R');

	# R needs both groups >= 2 unless var.equal makes n = 1 usable, which is
	# exactly what reg-tests-1a.R:4529 pins.  Welch with n = 1 has no df.
	$r = eval { t_test([2, 3, 5], [1.5]) };
	ok(!defined $r, 'Welch with a single y observation is fatal');
	$r = eval { t_test([2, 3, 5], [1.5], var_equal => 1) };
	ok(ref $r, 'the same call with var_equal => 1 succeeds, as in R');

	# t.test(<Inf>...) -- reg-tests-1e.R:1985, PR#18901.  R returns estimate
	# Inf with an NA p-value and NA conf.int rather than erroring, and these
	# calls errored in R <= 4.5.1.  The two references disagree on the details,
	# so all that is asserted is that a non-finite observation does not take
	# the process down.
	$r = eval { t_test([1 .. 6, $INF]) };
	ok(1, 'a non-finite observation does not crash the process');
}

#
# Both spellings of the two dotted R argument names.  'conf.level' is what this
# function's own documentation lists and was a croak until the fix noted above;
# 'var.equal' is R's spelling, which every sibling already accepted.
#
{
	my $u = t_test([1 .. 10], [7 .. 20], conf_level => 0.99, var_equal => 1);
	my $d = t_test([1 .. 10], [7 .. 20], 'conf.level' => 0.99, 'var.equal' => 1);
	is($d->{'p.value'},     $u->{'p.value'},     "'var.equal' == 'var_equal'");
	is($d->{'conf.int'}[0], $u->{'conf.int'}[0], "'conf.level' == 'conf_level' (lower)");
	is($d->{'conf.int'}[1], $u->{'conf.int'}[1], "'conf.level' == 'conf_level' (upper)");

	# The level must actually be used, so that accepting the argument cannot be
	# mistaken for ignoring it -- which is the other way the croak could have
	# been made to go away.
	my $narrow = t_test([1 .. 10], [7 .. 20], 'conf.level' => 0.90);
	my $wide   = t_test([1 .. 10], [7 .. 20], 'conf.level' => 0.999);
	cmp_ok($wide->{'conf.int'}[0], '<', $narrow->{'conf.int'}[0],
		'a higher conf.level really widens the interval');
	cmp_ok($wide->{'conf.int'}[1], '>', $narrow->{'conf.int'}[1],
		'...on both sides');
}

# An unrecognised alternative must be fatal rather than silently two-sided;
# SciPy raises ValueError and R errors on the partial match.
{
	my $r = eval { t_test([1, 2, 3], mu => 0, alternative => 'error') };
	ok(!defined $r, 'an unknown alternative is fatal');
	# SciPy spells the two-sided alternative with a hyphen; both must work.
	my $a = t_test([1, 2, 3], mu => 0, alternative => 'two.sided');
	my $b = t_test([1, 2, 3], mu => 0, alternative => 'two-sided');
	my $c = t_test([1, 2, 3], mu => 0, alternative => 'two_sided');
	is($a->{'p.value'}, $b->{'p.value'}, "SciPy's 'two-sided' spelling agrees");
	is($a->{'p.value'}, $c->{'p.value'}, "the 'two_sided' spelling agrees");
}

diag(sprintf 'worst relative error vs R: %s',
	join ', ', map { sprintf '%s %.3g', $_, $worst{$_} } sort keys %worst);

done_testing();
__DATA__
# ---- R 4.6.1, generated by t/t_test.R.R ----
# label  n_est  statistic  df  p.value  estimate(s)  ci_lo  ci_hi   (tab separated)
man.1to10.7to20|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-5.4349297638940595	21.982212340188994	1.8552818325118112e-05	5.5,13.5	-11.052801725158162	-4.9471982748418393
man.1to10.7to20|2s|two.sided|ve=0|mu=0|cl=0.9|p=0	2	-5.4349297638940595	21.982212340188994	1.8552818325118112e-05	5.5,13.5	-10.527657910657886	-5.4723420893421153
man.1to10.7to20|2s|two.sided|ve=0|mu=1.5|cl=0.95|p=0	2	-6.4539790946241951	21.982212340188994	1.7180173372534759e-06	5.5,13.5	-11.05280172515816	-4.9471982748418393
man.1to10.7to20|2s|two.sided|ve=0|mu=1.5|cl=0.9|p=0	2	-6.4539790946241951	21.982212340188994	1.7180173372534759e-06	5.5,13.5	-10.527657910657885	-5.4723420893421153
man.1to10.7to20|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-5.1472928473046853	22	3.6905772159119434e-05	5.5,13.5	-11.223244729881625	-4.7767552701183762
man.1to10.7to20|2s|two.sided|ve=1|mu=0|cl=0.9|p=0	2	-5.1472928473046853	22	3.6905772159119434e-05	5.5,13.5	-10.668811626335817	-5.3311883736641823
man.1to10.7to20|2s|two.sided|ve=1|mu=1.5|cl=0.95|p=0	2	-6.1124102561743134	22	3.7524172384836096e-06	5.5,13.5	-11.223244729881623	-4.7767552701183762
man.1to10.7to20|2s|two.sided|ve=1|mu=1.5|cl=0.9|p=0	2	-6.1124102561743134	22	3.7524172384836096e-06	5.5,13.5	-10.668811626335817	-5.3311883736641814
man.1to10.7to20|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-5.4349297638940595	21.982212340188994	9.276409162559056e-06	5.5,13.5	-Inf	-5.4723420893421153
man.1to10.7to20|2s|less|ve=0|mu=0|cl=0.9|p=0	2	-5.4349297638940595	21.982212340188994	9.276409162559056e-06	5.5,13.5	-Inf	-6.055143441691424
man.1to10.7to20|2s|less|ve=0|mu=1.5|cl=0.95|p=0	2	-6.4539790946241951	21.982212340188994	8.5900866862673794e-07	5.5,13.5	-Inf	-5.4723420893421153
man.1to10.7to20|2s|less|ve=0|mu=1.5|cl=0.9|p=0	2	-6.4539790946241951	21.982212340188994	8.5900866862673794e-07	5.5,13.5	-Inf	-6.055143441691424
man.1to10.7to20|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-5.1472928473046853	22	1.8452886079559717e-05	5.5,13.5	-Inf	-5.3311883736641823
man.1to10.7to20|2s|less|ve=1|mu=0|cl=0.9|p=0	2	-5.1472928473046853	22	1.8452886079559717e-05	5.5,13.5	-Inf	-5.946513974148238
man.1to10.7to20|2s|less|ve=1|mu=1.5|cl=0.95|p=0	2	-6.1124102561743134	22	1.8762086192418048e-06	5.5,13.5	-Inf	-5.3311883736641814
man.1to10.7to20|2s|less|ve=1|mu=1.5|cl=0.9|p=0	2	-6.1124102561743134	22	1.8762086192418048e-06	5.5,13.5	-Inf	-5.9465139741482371
man.1to10.7to20|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-5.4349297638940595	21.982212340188994	0.9999907235908374	5.5,13.5	-10.527657910657886	Inf
man.1to10.7to20|2s|greater|ve=0|mu=0|cl=0.9|p=0	2	-5.4349297638940595	21.982212340188994	0.9999907235908374	5.5,13.5	-9.9448565583085777	Inf
man.1to10.7to20|2s|greater|ve=0|mu=1.5|cl=0.95|p=0	2	-6.4539790946241951	21.982212340188994	0.99999914099133136	5.5,13.5	-10.527657910657885	Inf
man.1to10.7to20|2s|greater|ve=0|mu=1.5|cl=0.9|p=0	2	-6.4539790946241951	21.982212340188994	0.99999914099133136	5.5,13.5	-9.944856558308576	Inf
man.1to10.7to20|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-5.1472928473046853	22	0.9999815471139204	5.5,13.5	-10.668811626335817	Inf
man.1to10.7to20|2s|greater|ve=1|mu=0|cl=0.9|p=0	2	-5.1472928473046853	22	0.9999815471139204	5.5,13.5	-10.053486025851761	Inf
man.1to10.7to20|2s|greater|ve=1|mu=1.5|cl=0.95|p=0	2	-6.1124102561743134	22	0.99999812379138076	5.5,13.5	-10.668811626335817	Inf
man.1to10.7to20|2s|greater|ve=1|mu=1.5|cl=0.9|p=0	2	-6.1124102561743134	22	0.99999812379138076	5.5,13.5	-10.053486025851761	Inf
man.1to10.outlier|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-1.6329026332012053	14.164598953012469	0.12451349808974535	5.5,25.933333333333334	-47.24289988710192	6.3762332204352523
man.1to10.outlier|2s|two.sided|ve=0|mu=0|cl=0.9|p=0	2	-1.6329026332012053	14.164598953012469	0.12451349808974535	5.5,25.933333333333334	-42.455411390389457	1.5887447237227912
man.1to10.outlier|2s|two.sided|ve=0|mu=1.5|cl=0.95|p=0	2	-1.7527731364541486	14.164598953012469	0.1012481273283508	5.5,25.933333333333334	-47.24289988710192	6.3762332204352532
man.1to10.outlier|2s|two.sided|ve=0|mu=1.5|cl=0.9|p=0	2	-1.7527731364541486	14.164598953012469	0.1012481273283508	5.5,25.933333333333334	-42.455411390389457	1.5887447237227919
man.1to10.outlier|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-1.3259214390481338	23	0.19788422613063794	5.5,25.933333333333334	-52.312726230528007	11.446059563861342
man.1to10.outlier|2s|two.sided|ve=1|mu=0|cl=0.9|p=0	2	-1.3259214390481338	23	0.19788422613063794	5.5,25.933333333333334	-46.845236169828127	5.9785695031614665
man.1to10.outlier|2s|two.sided|ve=1|mu=1.5|cl=0.95|p=0	2	-1.4232566180973443	23	0.16808584642561686	5.5,25.933333333333334	-52.312726230528007	11.446059563861342
man.1to10.outlier|2s|two.sided|ve=1|mu=1.5|cl=0.9|p=0	2	-1.4232566180973443	23	0.16808584642561686	5.5,25.933333333333334	-46.845236169828134	5.9785695031614665
man.1to10.outlier|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-1.6329026332012053	14.164598953012469	0.062256749044872675	5.5,25.933333333333334	-Inf	1.5887447237227912
man.1to10.outlier|2s|less|ve=0|mu=0|cl=0.9|p=0	2	-1.6329026332012053	14.164598953012469	0.062256749044872675	5.5,25.933333333333334	-Inf	-3.6119674461692841
man.1to10.outlier|2s|less|ve=0|mu=1.5|cl=0.95|p=0	2	-1.7527731364541486	14.164598953012469	0.050624063664175399	5.5,25.933333333333334	-Inf	1.5887447237227919
man.1to10.outlier|2s|less|ve=0|mu=1.5|cl=0.9|p=0	2	-1.7527731364541486	14.164598953012469	0.050624063664175399	5.5,25.933333333333334	-Inf	-3.6119674461692837
man.1to10.outlier|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-1.3259214390481338	23	0.098942113065318971	5.5,25.933333333333334	-Inf	5.9785695031614665
man.1to10.outlier|2s|less|ve=1|mu=0|cl=0.9|p=0	2	-1.3259214390481338	23	0.098942113065318971	5.5,25.933333333333334	-Inf	-0.099571387679455198
man.1to10.outlier|2s|less|ve=1|mu=1.5|cl=0.95|p=0	2	-1.4232566180973443	23	0.084042923212808429	5.5,25.933333333333334	-Inf	5.9785695031614665
man.1to10.outlier|2s|less|ve=1|mu=1.5|cl=0.9|p=0	2	-1.4232566180973443	23	0.084042923212808429	5.5,25.933333333333334	-Inf	-0.099571387679455947
man.1to10.outlier|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-1.6329026332012053	14.164598953012469	0.93774325095512734	5.5,25.933333333333334	-42.455411390389457	Inf
man.1to10.outlier|2s|greater|ve=0|mu=0|cl=0.9|p=0	2	-1.6329026332012053	14.164598953012469	0.93774325095512734	5.5,25.933333333333334	-37.254699220497379	Inf
man.1to10.outlier|2s|greater|ve=0|mu=1.5|cl=0.95|p=0	2	-1.7527731364541486	14.164598953012469	0.94937593633582462	5.5,25.933333333333334	-42.455411390389457	Inf
man.1to10.outlier|2s|greater|ve=0|mu=1.5|cl=0.9|p=0	2	-1.7527731364541486	14.164598953012469	0.94937593633582462	5.5,25.933333333333334	-37.254699220497379	Inf
man.1to10.outlier|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-1.3259214390481338	23	0.90105788693468103	5.5,25.933333333333334	-46.845236169828127	Inf
man.1to10.outlier|2s|greater|ve=1|mu=0|cl=0.9|p=0	2	-1.3259214390481338	23	0.90105788693468103	5.5,25.933333333333334	-40.767095278987213	Inf
man.1to10.outlier|2s|greater|ve=1|mu=1.5|cl=0.95|p=0	2	-1.4232566180973443	23	0.91595707678719163	5.5,25.933333333333334	-46.845236169828134	Inf
man.1to10.outlier|2s|greater|ve=1|mu=1.5|cl=0.9|p=0	2	-1.4232566180973443	23	0.91595707678719163	5.5,25.933333333333334	-40.767095278987213	Inf
man.mtcars.am|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-3.7671231451449252	18.332251638400461	0.0013736383330710284	17.147368421052633,24.392307692307693	-11.280194355040161	-3.2096841874699598
man.mtcars.am|2s|two.sided|ve=0|mu=0|cl=0.9|p=0	2	-3.7671231451449252	18.332251638400461	0.0013736383330710284	17.147368421052633,24.392307692307693	-10.576622725562062	-3.9132558169480571
man.mtcars.am|2s|two.sided|ve=0|mu=1.5|cl=0.95|p=0	2	-4.5470723629578309	18.332251638400461	0.00023931282378420333	17.147368421052633,24.392307692307693	-11.280194355040161	-3.2096841874699598
man.mtcars.am|2s|two.sided|ve=0|mu=1.5|cl=0.9|p=0	2	-4.5470723629578309	18.332251638400461	0.00023931282378420333	17.147368421052633,24.392307692307693	-10.576622725562062	-3.9132558169480571
man.mtcars.am|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-4.1061269831006904	30	0.00028502074393506728	17.147368421052633,24.392307692307693	-10.848368970861245	-3.641509571648875
man.mtcars.am|2s|two.sided|ve=1|mu=0|cl=0.9|p=0	2	-4.1061269831006904	30	0.00028502074393506728	17.147368421052633,24.392307692307693	-10.239623094102681	-4.2502554484074402
man.mtcars.am|2s|two.sided|ve=1|mu=1.5|cl=0.95|p=0	2	-4.9562639192497855	30	2.6358305945301005e-05	17.147368421052633,24.392307692307693	-10.848368970861245	-3.641509571648875
man.mtcars.am|2s|two.sided|ve=1|mu=1.5|cl=0.9|p=0	2	-4.9562639192497855	30	2.6358305945301005e-05	17.147368421052633,24.392307692307693	-10.239623094102681	-4.2502554484074402
man.mtcars.am|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-3.7671231451449252	18.332251638400461	0.00068681916653551419	17.147368421052633,24.392307692307693	-Inf	-3.9132558169480571
man.mtcars.am|2s|less|ve=0|mu=0|cl=0.9|p=0	2	-3.7671231451449252	18.332251638400461	0.00068681916653551419	17.147368421052633,24.392307692307693	-Inf	-4.6880942772018503
man.mtcars.am|2s|less|ve=0|mu=1.5|cl=0.95|p=0	2	-4.5470723629578309	18.332251638400461	0.00011965641189210166	17.147368421052633,24.392307692307693	-Inf	-3.9132558169480571
man.mtcars.am|2s|less|ve=0|mu=1.5|cl=0.9|p=0	2	-4.5470723629578309	18.332251638400461	0.00011965641189210166	17.147368421052633,24.392307692307693	-Inf	-4.6880942772018503
man.mtcars.am|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-4.1061269831006904	30	0.00014251037196753364	17.147368421052633,24.392307692307693	-Inf	-4.2502554484074402
man.mtcars.am|2s|less|ve=1|mu=0|cl=0.9|p=0	2	-4.1061269831006904	30	0.00014251037196753364	17.147368421052633,24.392307692307693	-Inf	-4.9328146540247291
man.mtcars.am|2s|less|ve=1|mu=1.5|cl=0.95|p=0	2	-4.9562639192497855	30	1.3179152972650503e-05	17.147368421052633,24.392307692307693	-Inf	-4.2502554484074402
man.mtcars.am|2s|less|ve=1|mu=1.5|cl=0.9|p=0	2	-4.9562639192497855	30	1.3179152972650503e-05	17.147368421052633,24.392307692307693	-Inf	-4.9328146540247291
man.mtcars.am|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-3.7671231451449252	18.332251638400461	0.99931318083346454	17.147368421052633,24.392307692307693	-10.576622725562062	Inf
man.mtcars.am|2s|greater|ve=0|mu=0|cl=0.9|p=0	2	-3.7671231451449252	18.332251638400461	0.99931318083346454	17.147368421052633,24.392307692307693	-9.8017842653082692	Inf
man.mtcars.am|2s|greater|ve=0|mu=1.5|cl=0.95|p=0	2	-4.5470723629578309	18.332251638400461	0.99988034358810784	17.147368421052633,24.392307692307693	-10.576622725562062	Inf
man.mtcars.am|2s|greater|ve=0|mu=1.5|cl=0.9|p=0	2	-4.5470723629578309	18.332251638400461	0.99988034358810784	17.147368421052633,24.392307692307693	-9.8017842653082692	Inf
man.mtcars.am|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-4.1061269831006904	30	0.99985748962803245	17.147368421052633,24.392307692307693	-10.239623094102681	Inf
man.mtcars.am|2s|greater|ve=1|mu=0|cl=0.9|p=0	2	-4.1061269831006904	30	0.99985748962803245	17.147368421052633,24.392307692307693	-9.5570638884853913	Inf
man.mtcars.am|2s|greater|ve=1|mu=1.5|cl=0.95|p=0	2	-4.9562639192497855	30	0.99998682084702728	17.147368421052633,24.392307692307693	-10.239623094102681	Inf
man.mtcars.am|2s|greater|ve=1|mu=1.5|cl=0.9|p=0	2	-4.9562639192497855	30	0.99998682084702728	17.147368421052633,24.392307692307693	-9.5570638884853913	Inf
man.sleep.all|1s|two.sided|mu=0|cl=0.95	1	3.4129649952701091	19	0.0029176204041541161	1.54	0.59558449961960391	2.484415500380396
man.sleep.all|1s|two.sided|mu=0|cl=0.9	1	3.4129649952701091	19	0.0029176204041541161	1.54	0.75977971252759258	2.3202202874724072
man.sleep.all|1s|two.sided|mu=0|cl=0.99	1	3.4129649952701091	19	0.0029176204041541161	1.54	0.24908746498661924	2.8309125350133812
man.sleep.all|1s|two.sided|mu=0.5|cl=0.95	1	2.3048594773252686	19	0.032625933646171432	1.54	0.59558449961960402	2.4844155003803965
man.sleep.all|1s|two.sided|mu=0.5|cl=0.9	1	2.3048594773252686	19	0.032625933646171432	1.54	0.75977971252759269	2.3202202874724076
man.sleep.all|1s|two.sided|mu=0.5|cl=0.99	1	2.3048594773252686	19	0.032625933646171432	1.54	0.24908746498661927	2.8309125350133808
man.sleep.all|1s|two.sided|mu=-2|cl=0.95	1	7.8453870670494714	19	2.2367435483008208e-07	1.54	0.59558449961960358	2.484415500380396
man.sleep.all|1s|two.sided|mu=-2|cl=0.9	1	7.8453870670494714	19	2.2367435483008208e-07	1.54	0.75977971252759247	2.3202202874724076
man.sleep.all|1s|two.sided|mu=-2|cl=0.99	1	7.8453870670494714	19	2.2367435483008208e-07	1.54	0.24908746498661927	2.8309125350133808
man.sleep.all|1s|less|mu=0|cl=0.95	1	3.4129649952701091	19	0.99854118979792295	1.54	-Inf	2.3202202874724072
man.sleep.all|1s|less|mu=0|cl=0.9	1	3.4129649952701091	19	0.99854118979792295	1.54	-Inf	2.1390982751756726
man.sleep.all|1s|less|mu=0|cl=0.99	1	3.4129649952701091	19	0.99854118979792295	1.54	-Inf	2.6858670449244952
man.sleep.all|1s|less|mu=0.5|cl=0.95	1	2.3048594773252686	19	0.9836870331769143	1.54	-Inf	2.3202202874724076
man.sleep.all|1s|less|mu=0.5|cl=0.9	1	2.3048594773252686	19	0.9836870331769143	1.54	-Inf	2.1390982751756726
man.sleep.all|1s|less|mu=0.5|cl=0.99	1	2.3048594773252686	19	0.9836870331769143	1.54	-Inf	2.6858670449244948
man.sleep.all|1s|less|mu=-2|cl=0.95	1	7.8453870670494714	19	0.99999988816282259	1.54	-Inf	2.3202202874724076
man.sleep.all|1s|less|mu=-2|cl=0.9	1	7.8453870670494714	19	0.99999988816282259	1.54	-Inf	2.1390982751756731
man.sleep.all|1s|less|mu=-2|cl=0.99	1	7.8453870670494714	19	0.99999988816282259	1.54	-Inf	2.6858670449244952
man.sleep.all|1s|greater|mu=0|cl=0.95	1	3.4129649952701091	19	0.001458810202077058	1.54	0.75977971252759258	Inf
man.sleep.all|1s|greater|mu=0|cl=0.9	1	3.4129649952701091	19	0.001458810202077058	1.54	0.94090172482432743	Inf
man.sleep.all|1s|greater|mu=0|cl=0.99	1	3.4129649952701091	19	0.001458810202077058	1.54	0.39413295507550522	Inf
man.sleep.all|1s|greater|mu=0.5|cl=0.95	1	2.3048594773252686	19	0.016312966823085716	1.54	0.75977971252759269	Inf
man.sleep.all|1s|greater|mu=0.5|cl=0.9	1	2.3048594773252686	19	0.016312966823085716	1.54	0.94090172482432755	Inf
man.sleep.all|1s|greater|mu=0.5|cl=0.99	1	2.3048594773252686	19	0.016312966823085716	1.54	0.39413295507550528	Inf
man.sleep.all|1s|greater|mu=-2|cl=0.95	1	7.8453870670494714	19	1.1183717741504104e-07	1.54	0.75977971252759247	Inf
man.sleep.all|1s|greater|mu=-2|cl=0.9	1	7.8453870670494714	19	1.1183717741504104e-07	1.54	0.94090172482432743	Inf
man.sleep.all|1s|greater|mu=-2|cl=0.99	1	7.8453870670494714	19	1.1183717741504104e-07	1.54	0.39413295507550528	Inf
man.sleep.paired|2s|two.sided|ve=0|mu=0|cl=0.95|p=1	1	-4.0621276833820366	9	0.0028328901973842702	-1.5800000000000001	-2.4598857632769824	-0.70011423672301754
man.sleep.paired|2s|two.sided|ve=0|mu=0|cl=0.9|p=1	1	-4.0621276833820366	9	0.0028328901973842702	-1.5800000000000001	-2.2930052670292835	-0.8669947329707165
man.sleep.paired|2s|two.sided|ve=0|mu=1.5|cl=0.95|p=1	1	-7.9185780157067551	9	2.4017648644907359e-05	-1.5800000000000001	-2.4598857632769828	-0.70011423672301731
man.sleep.paired|2s|two.sided|ve=0|mu=1.5|cl=0.9|p=1	1	-7.9185780157067551	9	2.4017648644907359e-05	-1.5800000000000001	-2.2930052670292835	-0.86699473297071661
man.sleep.paired|2s|two.sided|ve=1|mu=0|cl=0.95|p=1	1	-4.0621276833820366	9	0.0028328901973842702	-1.5800000000000001	-2.4598857632769824	-0.70011423672301754
man.sleep.paired|2s|two.sided|ve=1|mu=0|cl=0.9|p=1	1	-4.0621276833820366	9	0.0028328901973842702	-1.5800000000000001	-2.2930052670292835	-0.8669947329707165
man.sleep.paired|2s|two.sided|ve=1|mu=1.5|cl=0.95|p=1	1	-7.9185780157067551	9	2.4017648644907359e-05	-1.5800000000000001	-2.4598857632769828	-0.70011423672301731
man.sleep.paired|2s|two.sided|ve=1|mu=1.5|cl=0.9|p=1	1	-7.9185780157067551	9	2.4017648644907359e-05	-1.5800000000000001	-2.2930052670292835	-0.86699473297071661
man.sleep.paired|2s|less|ve=0|mu=0|cl=0.95|p=1	1	-4.0621276833820366	9	0.0014164450986921351	-1.5800000000000001	-Inf	-0.8669947329707165
man.sleep.paired|2s|less|ve=0|mu=0|cl=0.9|p=1	1	-4.0621276833820366	9	0.0014164450986921351	-1.5800000000000001	-Inf	-1.0420589068122688
man.sleep.paired|2s|less|ve=0|mu=1.5|cl=0.95|p=1	1	-7.9185780157067551	9	1.2008824322453679e-05	-1.5800000000000001	-Inf	-0.86699473297071661
man.sleep.paired|2s|less|ve=0|mu=1.5|cl=0.9|p=1	1	-7.9185780157067551	9	1.2008824322453679e-05	-1.5800000000000001	-Inf	-1.0420589068122688
man.sleep.paired|2s|less|ve=1|mu=0|cl=0.95|p=1	1	-4.0621276833820366	9	0.0014164450986921351	-1.5800000000000001	-Inf	-0.8669947329707165
man.sleep.paired|2s|less|ve=1|mu=0|cl=0.9|p=1	1	-4.0621276833820366	9	0.0014164450986921351	-1.5800000000000001	-Inf	-1.0420589068122688
man.sleep.paired|2s|less|ve=1|mu=1.5|cl=0.95|p=1	1	-7.9185780157067551	9	1.2008824322453679e-05	-1.5800000000000001	-Inf	-0.86699473297071661
man.sleep.paired|2s|less|ve=1|mu=1.5|cl=0.9|p=1	1	-7.9185780157067551	9	1.2008824322453679e-05	-1.5800000000000001	-Inf	-1.0420589068122688
man.sleep.paired|2s|greater|ve=0|mu=0|cl=0.95|p=1	1	-4.0621276833820366	9	0.99858355490130779	-1.5800000000000001	-2.2930052670292835	Inf
man.sleep.paired|2s|greater|ve=0|mu=0|cl=0.9|p=1	1	-4.0621276833820366	9	0.99858355490130779	-1.5800000000000001	-2.1179410931877314	Inf
man.sleep.paired|2s|greater|ve=0|mu=1.5|cl=0.95|p=1	1	-7.9185780157067551	9	0.99998799117567749	-1.5800000000000001	-2.2930052670292835	Inf
man.sleep.paired|2s|greater|ve=0|mu=1.5|cl=0.9|p=1	1	-7.9185780157067551	9	0.99998799117567749	-1.5800000000000001	-2.1179410931877314	Inf
man.sleep.paired|2s|greater|ve=1|mu=0|cl=0.95|p=1	1	-4.0621276833820366	9	0.99858355490130779	-1.5800000000000001	-2.2930052670292835	Inf
man.sleep.paired|2s|greater|ve=1|mu=0|cl=0.9|p=1	1	-4.0621276833820366	9	0.99858355490130779	-1.5800000000000001	-2.1179410931877314	Inf
man.sleep.paired|2s|greater|ve=1|mu=1.5|cl=0.95|p=1	1	-7.9185780157067551	9	0.99998799117567749	-1.5800000000000001	-2.2930052670292835	Inf
man.sleep.paired|2s|greater|ve=1|mu=1.5|cl=0.9|p=1	1	-7.9185780157067551	9	0.99998799117567749	-1.5800000000000001	-2.1179410931877314	Inf
man.sleep.unpaired|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-1.8608134674868531	17.776473516178498	0.079394140187358173	0.75,2.3300000000000001	-3.3654832307117104	0.20548323071171018
man.sleep.unpaired|2s|two.sided|ve=0|mu=0|cl=0.9|p=0	2	-1.8608134674868531	17.776473516178498	0.079394140187358173	0.75,2.3300000000000001	-3.0533814973316065	-0.10661850266839384
man.sleep.unpaired|2s|two.sided|ve=0|mu=1.5|cl=0.95|p=0	2	-3.6274085315566502	17.776473516178498	0.001958689489248005	0.75,2.3300000000000001	-3.3654832307117104	0.20548323071171026
man.sleep.unpaired|2s|two.sided|ve=0|mu=1.5|cl=0.9|p=0	2	-3.6274085315566502	17.776473516178498	0.001958689489248005	0.75,2.3300000000000001	-3.0533814973316069	-0.1066185026683939
man.sleep.unpaired|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-1.8608134674868528	18	0.079186714215938175	0.75,2.3300000000000001	-3.3638740322875984	0.20387403228759859
man.sleep.unpaired|2s|two.sided|ve=1|mu=0|cl=0.9|p=0	2	-1.8608134674868528	18	0.079186714215938175	0.75,2.3300000000000001	-3.0523778316996024	-0.10762216830039782
man.sleep.unpaired|2s|two.sided|ve=1|mu=1.5|cl=0.95|p=0	2	-3.6274085315566498	18	0.0019260866305859867	0.75,2.3300000000000001	-3.3638740322875984	0.20387403228759848
man.sleep.unpaired|2s|two.sided|ve=1|mu=1.5|cl=0.9|p=0	2	-3.6274085315566498	18	0.0019260866305859867	0.75,2.3300000000000001	-3.0523778316996024	-0.10762216830039795
man.sleep.unpaired|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-1.8608134674868531	17.776473516178498	0.039697070093679086	0.75,2.3300000000000001	-Inf	-0.10661850266839384
man.sleep.unpaired|2s|less|ve=0|mu=0|cl=0.9|p=0	2	-1.8608134674868531	17.776473516178498	0.039697070093679086	0.75,2.3300000000000001	-Inf	-0.44983552414302425
man.sleep.unpaired|2s|less|ve=0|mu=1.5|cl=0.95|p=0	2	-3.6274085315566502	17.776473516178498	0.00097934474462400248	0.75,2.3300000000000001	-Inf	-0.1066185026683939
man.sleep.unpaired|2s|less|ve=0|mu=1.5|cl=0.9|p=0	2	-3.6274085315566502	17.776473516178498	0.00097934474462400248	0.75,2.3300000000000001	-Inf	-0.44983552414302408
man.sleep.unpaired|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-1.8608134674868528	18	0.039593357107969088	0.75,2.3300000000000001	-Inf	-0.10762216830039782
man.sleep.unpaired|2s|less|ve=1|mu=0|cl=0.9|p=0	2	-1.8608134674868528	18	0.039593357107969088	0.75,2.3300000000000001	-Inf	-0.45037700039898942
man.sleep.unpaired|2s|less|ve=1|mu=1.5|cl=0.95|p=0	2	-3.6274085315566498	18	0.00096304331529299333	0.75,2.3300000000000001	-Inf	-0.10762216830039795
man.sleep.unpaired|2s|less|ve=1|mu=1.5|cl=0.9|p=0	2	-3.6274085315566498	18	0.00096304331529299333	0.75,2.3300000000000001	-Inf	-0.45037700039898931
man.sleep.unpaired|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-1.8608134674868531	17.776473516178498	0.96030292990632093	0.75,2.3300000000000001	-3.0533814973316065	Inf
man.sleep.unpaired|2s|greater|ve=0|mu=0|cl=0.9|p=0	2	-1.8608134674868531	17.776473516178498	0.96030292990632093	0.75,2.3300000000000001	-2.7101644758569763	Inf
man.sleep.unpaired|2s|greater|ve=0|mu=1.5|cl=0.95|p=0	2	-3.6274085315566502	17.776473516178498	0.99902065525537598	0.75,2.3300000000000001	-3.0533814973316069	Inf
man.sleep.unpaired|2s|greater|ve=0|mu=1.5|cl=0.9|p=0	2	-3.6274085315566502	17.776473516178498	0.99902065525537598	0.75,2.3300000000000001	-2.7101644758569758	Inf
man.sleep.unpaired|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-1.8608134674868528	18	0.96040664289203093	0.75,2.3300000000000001	-3.0523778316996024	Inf
man.sleep.unpaired|2s|greater|ve=1|mu=0|cl=0.9|p=0	2	-1.8608134674868528	18	0.96040664289203093	0.75,2.3300000000000001	-2.7096229996010108	Inf
man.sleep.unpaired|2s|greater|ve=1|mu=1.5|cl=0.95|p=0	2	-3.6274085315566498	18	0.99903695668470704	0.75,2.3300000000000001	-3.0523778316996024	Inf
man.sleep.unpaired|2s|greater|ve=1|mu=1.5|cl=0.9|p=0	2	-3.6274085315566498	18	0.99903695668470704	0.75,2.3300000000000001	-2.7096229996010113	Inf
reg2.1to28|1s|two.sided|mu=0|cl=0.95	1	9.3273790530888139	27	6.1885389180443769e-10	14.5	11.31029983668223	17.68970016331777
reg2.1to28|1s|two.sided|mu=0|cl=0.9	1	9.3273790530888139	27	6.1885389180443769e-10	14.5	11.852130505000538	17.147869494999462
reg2.1to28|1s|two.sided|mu=0|cl=0.99	1	9.3273790530888139	27	6.1885389180443769e-10	14.5	10.192798303831351	18.807201696168647
reg2.1to28|1s|two.sided|mu=0.5|cl=0.95	1	9.0057452926374761	27	1.277483498970105e-09	14.5	11.310299836682232	17.68970016331777
reg2.1to28|1s|two.sided|mu=0.5|cl=0.9	1	9.0057452926374761	27	1.277483498970105e-09	14.5	11.852130505000538	17.147869494999462
reg2.1to28|1s|two.sided|mu=0.5|cl=0.99	1	9.0057452926374761	27	1.277483498970105e-09	14.5	10.192798303831351	18.807201696168651
reg2.1to28|1s|two.sided|mu=-2|cl=0.95	1	10.613914094894168	27	3.8950108350063723e-11	14.5	11.310299836682232	17.68970016331777
reg2.1to28|1s|two.sided|mu=-2|cl=0.9	1	10.613914094894168	27	3.8950108350063723e-11	14.5	11.852130505000538	17.147869494999462
reg2.1to28|1s|two.sided|mu=-2|cl=0.99	1	10.613914094894168	27	3.8950108350063723e-11	14.5	10.192798303831351	18.807201696168651
reg2.1to28|1s|less|mu=0|cl=0.95	1	9.3273790530888139	27	0.99999999969057307	14.5	-Inf	17.147869494999462
reg2.1to28|1s|less|mu=0|cl=0.9	1	9.3273790530888139	27	0.99999999969057307	14.5	-Inf	16.542234171850922
reg2.1to28|1s|less|mu=0|cl=0.99	1	9.3273790530888139	27	0.99999999969057307	14.5	-Inf	18.343906044698478
reg2.1to28|1s|less|mu=0.5|cl=0.95	1	9.0057452926374761	27	0.99999999936125827	14.5	-Inf	17.147869494999462
reg2.1to28|1s|less|mu=0.5|cl=0.9	1	9.0057452926374761	27	0.99999999936125827	14.5	-Inf	16.542234171850922
reg2.1to28|1s|less|mu=0.5|cl=0.99	1	9.0057452926374761	27	0.99999999936125827	14.5	-Inf	18.343906044698482
reg2.1to28|1s|less|mu=-2|cl=0.95	1	10.613914094894168	27	0.99999999998052491	14.5	-Inf	17.147869494999462
reg2.1to28|1s|less|mu=-2|cl=0.9	1	10.613914094894168	27	0.99999999998052491	14.5	-Inf	16.542234171850922
reg2.1to28|1s|less|mu=-2|cl=0.99	1	10.613914094894168	27	0.99999999998052491	14.5	-Inf	18.343906044698482
reg2.1to28|1s|greater|mu=0|cl=0.95	1	9.3273790530888139	27	3.0942694590221884e-10	14.5	11.852130505000538	Inf
reg2.1to28|1s|greater|mu=0|cl=0.9	1	9.3273790530888139	27	3.0942694590221884e-10	14.5	12.457765828149077	Inf
reg2.1to28|1s|greater|mu=0|cl=0.99	1	9.3273790530888139	27	3.0942694590221884e-10	14.5	10.656093955301518	Inf
reg2.1to28|1s|greater|mu=0.5|cl=0.95	1	9.0057452926374761	27	6.3874174948505251e-10	14.5	11.852130505000538	Inf
reg2.1to28|1s|greater|mu=0.5|cl=0.9	1	9.0057452926374761	27	6.3874174948505251e-10	14.5	12.457765828149077	Inf
reg2.1to28|1s|greater|mu=0.5|cl=0.99	1	9.0057452926374761	27	6.3874174948505251e-10	14.5	10.65609395530152	Inf
reg2.1to28|1s|greater|mu=-2|cl=0.95	1	10.613914094894168	27	1.9475054175031862e-11	14.5	11.852130505000538	Inf
reg2.1to28|1s|greater|mu=-2|cl=0.9	1	10.613914094894168	27	1.9475054175031862e-11	14.5	12.457765828149077	Inf
reg2.1to28|1s|greater|mu=-2|cl=0.99	1	10.613914094894168	27	1.9475054175031862e-11	14.5	10.65609395530152	Inf
reg1a.n1.xfirst|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-2.1895949947729489	4	0.093734447386094807	23,28.199999999999999	-11.793691793000114	1.393691793000116
reg1a.n1.yfirst|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	2.1895949947729489	4	0.093734447386094807	28.199999999999999,23	-1.393691793000116	11.793691793000114
reg1a.n1.xfirst|2s|two.sided|ve=1|mu=0|cl=0.99|p=0	2	-2.1895949947729489	4	0.093734447386094807	23,28.199999999999999	-16.134119500717325	5.7341195007173278
reg1a.n1.yfirst|2s|two.sided|ve=1|mu=0|cl=0.99|p=0	2	2.1895949947729489	4	0.093734447386094807	28.199999999999999,23	-5.7341195007173278	16.134119500717325
reg1a.n1.xfirst|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-2.1895949947729489	4	0.046867223693047404	23,28.199999999999999	-Inf	-0.13714439640098749
reg1a.n1.yfirst|2s|less|ve=1|mu=0|cl=0.95|p=0	2	2.1895949947729489	4	0.95313277630695259	28.199999999999999,23	-Inf	10.262855603599009
reg1a.n1.xfirst|2s|less|ve=1|mu=0|cl=0.99|p=0	2	-2.1895949947729489	4	0.046867223693047404	23,28.199999999999999	-Inf	3.6985070133996309
reg1a.n1.yfirst|2s|less|ve=1|mu=0|cl=0.99|p=0	2	2.1895949947729489	4	0.95313277630695259	28.199999999999999,23	-Inf	14.098507013399628
reg1a.n1.xfirst|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-2.1895949947729489	4	0.95313277630695259	23,28.199999999999999	-10.262855603599009	Inf
reg1a.n1.yfirst|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	2.1895949947729489	4	0.046867223693047404	28.199999999999999,23	0.13714439640098749	Inf
reg1a.n1.xfirst|2s|greater|ve=1|mu=0|cl=0.99|p=0	2	-2.1895949947729489	4	0.95313277630695259	23,28.199999999999999	-14.098507013399628	Inf
reg1a.n1.yfirst|2s|greater|ve=1|mu=0|cl=0.99|p=0	2	2.1895949947729489	4	0.046867223693047404	28.199999999999999,23	-3.6985070133996309	Inf
edge.two.pts|1s|two.sided|mu=0|cl=0.95	1	3	1	0.20483276469913345	1.5	-4.8531023680873471	7.8531023680873471
edge.two.pts|1s|two.sided|mu=1.5|cl=0.95	1	0	1	1	1.5	-4.8531023680873471	7.8531023680873471
edge.two.pts|1s|less|mu=0|cl=0.95	1	3	1	0.89758361765043326	1.5	-Inf	4.6568757573375184
edge.two.pts|1s|less|mu=1.5|cl=0.95	1	0	1	0.5	1.5	-Inf	4.6568757573375184
edge.two.pts|1s|greater|mu=0|cl=0.95	1	3	1	0.10241638234956672	1.5	-1.6568757573375188	Inf
edge.two.pts|1s|greater|mu=1.5|cl=0.95	1	0	1	0.5	1.5	-1.6568757573375188	Inf
edge.2v2|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-2.8284271247461898	2.0000000000000004	0.10557280900008413	1.5,3.5	-5.0424349222966542	1.0424349222966545
edge.2v2|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-2.8284271247461898	2	0.10557280900008414	1.5,3.5	-5.0424349222966542	1.0424349222966545
edge.2v2|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-2.8284271247461898	2.0000000000000004	0.052786404500042065	1.5,3.5	-Inf	0.064741604835054742
edge.2v2|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-2.8284271247461898	2	0.052786404500042072	1.5,3.5	-Inf	0.064741604835054742
edge.2v2|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-2.8284271247461898	2.0000000000000004	0.94721359549995787	1.5,3.5	-4.0647416048350546	Inf
edge.2v2|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-2.8284271247461898	2	0.94721359549995787	1.5,3.5	-4.0647416048350546	Inf
edge.2v3|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-3.2732683535398861	2.8823529411764697	0.049416256862577515	1.5,4	-4.9877337982053822	-0.012266201794617697
edge.2v3|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-3	3	0.057668885622437313	1.5,4	-5.1520385877364241	0.15203858773642315
edge.2v3|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-3.2732683535398861	2.8823529411764697	0.024708128431288758	1.5,4	-Inf	-0.6722821200471859
edge.2v3|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-3	3	0.028834442811218657	1.5,4	-Inf	-0.5388638043318128
edge.2v3|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-3.2732683535398861	2.8823529411764697	0.97529187156871122	1.5,4	-4.3277178799528144	Inf
edge.2v3|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-3	3	0.97116555718878139	1.5,4	-4.4611361956681872	Inf
edge.samemean|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	0	2.9411764705882351	1	2,2	-4.1553995031825037	4.1553995031825037
edge.samemean|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	0	4	1	2,2	-3.584375218030051	3.584375218030051
edge.samemean|2s|less|ve=0|mu=0|cl=0.95|p=0	2	0	2.9411764705882351	0.5	2,2	-Inf	3.0631119350028801
edge.samemean|2s|less|ve=1|mu=0|cl=0.95|p=0	2	0	4	0.5	2,2	-Inf	2.7522023667029711
edge.samemean|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	0	2.9411764705882351	0.5	2,2	-3.0631119350028801	Inf
edge.samemean|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	0	4	0.5	2,2	-2.7522023667029711	Inf
edge.onezerovar|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	5.196152422706632	2	0.035098718645984649	5,2	0.51586228824967006	5.4841377117503294
edge.onezerovar|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	5.196152422706632	4	0.0065333763389151464	5,2	1.397018671123835	4.6029813288761643
edge.onezerovar|2s|less|ve=0|mu=0|cl=0.95|p=0	2	5.196152422706632	2	0.98245064067700771	5,2	-Inf	4.6858544608470485
edge.onezerovar|2s|less|ve=1|mu=0|cl=0.95|p=0	2	5.196152422706632	4	0.99673331183054237	5,2	-Inf	4.2308223159567291
edge.onezerovar|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	5.196152422706632	2	0.017549359322992324	5,2	1.314145539152952	Inf
edge.onezerovar|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	5.196152422706632	4	0.0032666881694575732	5,2	1.7691776840432705	Inf
scipy.uneqvar.a|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-0.68649512735572626	3.4104431643463773	0.53619490753126686	2,2.7333333333333334	-3.9127771956452175	2.4461105289785507
scipy.uneqvar.a|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-0.68649512735572638	4	0.53012731536371505	2,2.7333333333333334	-3.6992098016111257	2.2325431349444593
scipy.uneqvar.a|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-0.68649512735572626	3.4104431643463773	0.26809745376563343	2,2.7333333333333334	-Inf	1.6619228528544006
scipy.uneqvar.a|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-0.68649512735572638	4	0.26506365768185752	2,2.7333333333333334	-Inf	1.5439651465476185
scipy.uneqvar.a|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-0.68649512735572626	3.4104431643463773	0.73190254623436657	2,2.7333333333333334	-3.1285895195210673	Inf
scipy.uneqvar.a|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-0.68649512735572638	4	0.73493634231814253	2,2.7333333333333334	-3.0106318132142849	Inf
scipy.uneqvar.b|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-0.21086633159507231	3.9030852720403559	0.84354139131608252	2.5,2.7333333333333334	-3.3359185532113456	2.8692518865446783
scipy.uneqvar.b|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-0.21770017209205411	5	0.83626813927969024	2.5,2.7333333333333334	-2.9885099716940724	2.5218433050274056
scipy.uneqvar.b|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-0.21086633159507231	3.9030852720403559	0.42177069565804126	2.5,2.7333333333333334	-Inf	2.1425842482066786
scipy.uneqvar.b|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-0.21770017209205411	5	0.41813406963984512	2.5,2.7333333333333334	-Inf	1.9264166992890177
scipy.uneqvar.b|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-0.21086633159507231	3.9030852720403559	0.57822930434195874	2.5,2.7333333333333334	-2.6092509148733454	Inf
scipy.uneqvar.b|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-0.21770017209205411	5	0.58186593036015488	2.5,2.7333333333333334	-2.3930833659556847	Inf
scipy.n1.235.15|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	1.039402300775375	2	0.40777990773601791	3.3333333333333335,1.5	-5.7558327338601849	9.4224994005268528
scipy.n1.235.15|2s|less|ve=1|mu=0|cl=0.95|p=0	2	1.039402300775375	2	0.79611004613199099	3.3333333333333335,1.5	-Inf	6.9837037850070436
scipy.n1.235.15|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	1.039402300775375	2	0.20388995386800896	3.3333333333333335,1.5	-3.3170371183403757	Inf
scipy.nan2nd|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	-2.3237900077244502	3	0.10272807885839903	1.5,3	-3.5542602567605206	0.55426025676052082
scipy.nan2nd|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	-2.5354627641855498	5	0.052181400457057867	1.5,3	-3.0207767228611098	0.020776722861109504
scipy.nan2nd|2s|less|ve=0|mu=0|cl=0.95|p=0	2	-2.3237900077244502	3	0.051364039429199516	1.5,3	-Inf	0.019089565093491773
scipy.nan2nd|2s|less|ve=1|mu=0|cl=0.95|p=0	2	-2.5354627641855498	5	0.026090700228528933	1.5,3	-Inf	-0.3078813056556739
scipy.nan2nd|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	-2.3237900077244502	3	0.94863596057080046	1.5,3	-3.0190895650934917	Inf
scipy.nan2nd|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	-2.5354627641855498	5	0.97390929977147112	1.5,3	-2.6921186943443263	Inf
scipy.X1|1s|two.sided|mu=0|cl=0.95	1	0	2	1	0	-2.4841377117503298	2.4841377117503298
scipy.X1|1s|two.sided|mu=1|cl=0.95	1	-1.7320508075688774	2	0.22540333075851657	0	-2.4841377117503298	2.4841377117503294
scipy.X1|1s|two.sided|mu=2|cl=0.95	1	-3.4641016151377548	2	0.074179900227448525	0	-2.4841377117503294	2.4841377117503298
scipy.X1|1s|less|mu=0|cl=0.95	1	0	2	0.5	0	-Inf	1.685854460847048
scipy.X1|1s|less|mu=1|cl=0.95	1	-1.7320508075688774	2	0.11270166537925828	0	-Inf	1.685854460847048
scipy.X1|1s|less|mu=2|cl=0.95	1	-3.4641016151377548	2	0.037089950113724263	0	-Inf	1.685854460847048
scipy.X1|1s|greater|mu=0|cl=0.95	1	0	2	0.5	0	-1.685854460847048	Inf
scipy.X1|1s|greater|mu=1|cl=0.95	1	-1.7320508075688774	2	0.8872983346207417	0	-1.685854460847048	Inf
scipy.X1|1s|greater|mu=2|cl=0.95	1	-3.4641016151377548	2	0.96291004988627571	0	-1.6858544608470476	Inf
scipy.X2|1s|two.sided|mu=0|cl=0.95	1	1.7320508075688774	2	0.22540333075851657	1	-1.4841377117503296	3.4841377117503298
scipy.X2|1s|less|mu=0|cl=0.95	1	1.7320508075688774	2	0.8872983346207417	1	-Inf	2.685854460847048
scipy.X2|1s|greater|mu=0|cl=0.95	1	1.7320508075688774	2	0.11270166537925828	1	-0.68585446084704793	Inf
scipy.rel.linspace|2s|two.sided|ve=0|mu=0|cl=0.95|p=1	1	0.81248591389165703	99	0.41846234511362157	0.00049999999999896124	-0.00072107775510836319	0.0017210777551062858
scipy.rel.linspace|2s|two.sided|ve=1|mu=0|cl=0.95|p=1	1	0.81248591389165703	99	0.41846234511362157	0.00049999999999896124	-0.00072107775510836319	0.0017210777551062858
scipy.rel.linspace|2s|less|ve=0|mu=0|cl=0.95|p=1	1	0.81248591389165703	99	0.79076882744318922	0.00049999999999896124	-Inf	0.0015217968875662639
scipy.rel.linspace|2s|less|ve=1|mu=0|cl=0.95|p=1	1	0.81248591389165703	99	0.79076882744318922	0.00049999999999896124	-Inf	0.0015217968875662639
scipy.rel.linspace|2s|greater|ve=0|mu=0|cl=0.95|p=1	1	0.81248591389165703	99	0.20923117255681078	0.00049999999999896124	-0.00052179688756834135	Inf
scipy.rel.linspace|2s|greater|ve=1|mu=0|cl=0.95|p=1	1	0.81248591389165703	99	0.20923117255681078	0.00049999999999896124	-0.00052179688756834135	Inf
scipy.ind.linspace|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	1.091274689792725	197.98000353474157	0.27647831993021538	55.000000000000007,50.5	-3.6318519019452054	12.63185190194522
scipy.ind.linspace|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	1.0912746897927252	198	0.27647818616352016	55.000000000000007,50.5	-3.6318468514549171	12.631846851454933
scipy.ind.linspace|2s|less|ve=0|mu=0|cl=0.95|p=0	2	1.091274689792725	197.98000353474157	0.86176084003489228	55.000000000000007,50.5	-Inf	11.314635789478031
scipy.ind.linspace|2s|less|ve=1|mu=0|cl=0.95|p=0	2	1.0912746897927252	198	0.86176090691823992	55.000000000000007,50.5	-Inf	11.314632553874064
scipy.ind.linspace|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	1.091274689792725	197.98000353474157	0.13823915996510769	55.000000000000007,50.5	-2.3146357894780154	Inf
scipy.ind.linspace|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	1.0912746897927252	198	0.13823909308176008	55.000000000000007,50.5	-2.3146325538740506	Inf
scipy.ind.linspace.uneqn|2s|two.sided|ve=0|mu=0|cl=0.95|p=0	2	0.66745638708050281	36.00928803430633	0.50873585065616655	55.000000000000007,50.5	-9.1733147581792363	18.173314758179252
scipy.ind.linspace.uneqn|2s|two.sided|ve=1|mu=0|cl=0.95|p=0	2	0.68188325826343421	123	0.49659476797881785	55.000000000000007,50.5	-8.5630485130323457	17.56304851303236
scipy.ind.linspace.uneqn|2s|less|ve=0|mu=0|cl=0.95|p=0	2	0.66745638708050281	36.00928803430633	0.74563207467191672	55.000000000000007,50.5	-Inf	15.882448521581738
scipy.ind.linspace.uneqn|2s|less|ve=1|mu=0|cl=0.95|p=0	2	0.68188325826343421	123	0.75170261601059107	55.000000000000007,50.5	-Inf	15.43737629768518
scipy.ind.linspace.uneqn|2s|greater|ve=0|mu=0|cl=0.95|p=0	2	0.66745638708050281	36.00928803430633	0.25436792532808328	55.000000000000007,50.5	-6.8824485215817228	Inf
scipy.ind.linspace.uneqn|2s|greater|ve=1|mu=0|cl=0.95|p=0	2	0.68188325826343421	123	0.24829738398940893	55.000000000000007,50.5	-6.4373762976851641	Inf
scipy.ci.11v13|2s|two.sided|ve=0|mu=0|cl=0.9|p=0	2	-0.23146070834839971	19.894434826822256	0.81932090565257698	0.4868133581818182,0.51605853384615386	-0.24722029381818847	0.18872994248951716
scipy.ci.11v13|2s|two.sided|ve=1|mu=0|cl=0.9|p=0	2	-0.23456253225550058	22	0.81671759056438165	0.4868133581818182,0.51605853384615386	-0.24333814433622503	0.18484779300755375
scipy.ci.11v13|2s|less|ve=0|mu=0|cl=0.9|p=0	2	-0.23146070834839971	19.894434826822256	0.40966045282628849	0.4868133581818182,0.51605853384615386	-Inf	0.13824264688611246
scipy.ci.11v13|2s|less|ve=1|mu=0|cl=0.9|p=0	2	-0.23456253225550058	22	0.40835879528219082	0.4868133581818182,0.51605853384615386	-Inf	0.13548616582957473
scipy.ci.11v13|2s|greater|ve=0|mu=0|cl=0.9|p=0	2	-0.23146070834839971	19.894434826822256	0.59033954717371151	0.4868133581818182,0.51605853384615386	-0.19673299821478377	Inf
scipy.ci.11v13|2s|greater|ve=1|mu=0|cl=0.9|p=0	2	-0.23456253225550058	22	0.59164120471780923	0.4868133581818182,0.51605853384615386	-0.19397651715824601	Inf
# ---- SciPy 1.18.0, scipy/stats/tests/test_stats.py, at SciPy's own values ----
# tag|form|alternative|ve=..|..   statistic  df  p.value  [ci_lo  ci_hi]
SCIPY-SECTION
scipy.uneqvar.a|2s|two.sided|ve=0	-0.686495127355726265	-	0.53619490753126686	-	-
scipy.uneqvar.b|2s|two.sided|ve=0	-0.210866331595072315	-	0.84354139131608252	-	-
scipy.n1.235.15|2s|two.sided|ve=1	1.0394023007754	2	0.407779907736	-	-
scipy.nan2nd|2s|two.sided|ve=1	-2.5354627641855498	5	0.052181400457057901	-	-
scipy.X1|1s|two.sided|mu=0	0.0	2	1.0	-	-
scipy.X1|1s|two.sided|mu=1	-1.7320508075689	2	0.2254033307585	-	-
scipy.X1|1s|two.sided|mu=2	-3.4641016151378	2	0.07417990022745	-	-
scipy.X1|1s|less|mu=1	-1.7320508075689	2	0.11270166537925	-	-
scipy.X1|1s|greater|mu=1	-1.7320508075689	2	0.88729833462075	-	-
scipy.X2|1s|two.sided|mu=0	1.7320508075689	2	0.2254033307585	-	-
scipy.rel.linspace|2s|two.sided|p=1	0.81248591389165692	99	0.41846234511362157	-	-
scipy.rel.linspace|2s|greater|p=1	0.81248591389165692	99	0.209231172556810785	-	-
scipy.rel.linspace|2s|less|p=1	0.81248591389165692	99	0.790768827443189215	-	-
scipy.ind.linspace|2s|two.sided|ve=0	1.0912746897927283	-	0.27647831993021388	-	-
scipy.ind.linspace.uneqn|2s|two.sided|ve=0	0.66745638708050492	-	0.50873585065616544	-	-
scipy.ci.11v13|2s|two.sided|ve=0|cl=0.9	-0.2314607	19.894435	0.8193209	-0.247220294	0.188729943
scipy.ci.11v13|2s|less|ve=0|cl=0.9	-0.2314607	19.894435	0.40966045	-Inf	0.1382426469
scipy.ci.11v13|2s|greater|ve=0|cl=0.9	-0.2314607	19.894435	0.5903395	-0.1967329982	Inf
scipy.ci.11v13|2s|two.sided|ve=1|cl=0.9	-0.2345625322555006	22	0.8167175905643815	-	-
scipy.ci.11v13|2s|less|ve=1|cl=0.9	-0.2345625322555006	22	0.4083587952821908	-	-
scipy.ci.11v13|2s|greater|ve=1|cl=0.9	-0.2345625322555006	22	0.5916412047178092	-	-
